# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VizApi")

api_instance <- VizApi$new()

test_that("ADDVIZ", {
  # tests for ADDVIZ
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Save a viz in the MetExplore3 database
  # Save a viz in the MetExplore3 database
  # @param viz Viz  (optional)
  # @return [VizResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ADDVIZFAVORITE", {
  # tests for ADDVIZFAVORITE
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Set a viz as favorite
  # Set a viz as favorite
  # @param viz_favorite VizFavorite  (optional)
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ADDVIZRIGHTS", {
  # tests for ADDVIZRIGHTS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Add a permission for a user to access a viz
  # Add a permission for a user to access a viz. Needs to be the owner of the viz
  # @param viz_right VizRight  (optional)
  # @return [VizResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("COPYVIZ", {
  # tests for COPYVIZ
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # copy a visualisation
  # copy a visualisation. The user must have the read rights on the visualisation.
  # @param copyviz_request COPYVIZRequest  (optional)
  # @return [VizResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DELVIZ", {
  # tests for DELVIZ
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Delete a saved visualisation in the MetExplore3 database
  # Delete a saved visualisation in the MetExplore3 database
  # @param delviz_request DELVIZRequest  (optional)
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DELVIZFAVORITE", {
  # tests for DELVIZFAVORITE
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Remove a viz as favorite
  # Remove a viz as favorite
  # @param viz_favorite VizFavorite  (optional)
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GETVIZ", {
  # tests for GETVIZ
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Get all private viz or one private viz
  # Get all saved visualisations or one saved visualisation if the id is provided. If the visualisation is private, the user must be authenticated and have the read rights on the visualisation.  The format parameter allows to get only the metadata of the network (name, description, etc...) (summary option) or the metadata plus the json graph (complete option). By default, the visualisations returned are public. Set the type parameter to private to get only private visualisations. 
  # @param id integer the viz id (optional)
  # @param format character format of the output (optional)
  # @param type character get only private visualisations (optional)
  # @return [GETVIZ200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UPDATEVIZ", {
  # tests for UPDATEVIZ
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # update a visualisation saved in the MetExplore 3 database
  # Update a visualisation saved in the MetExplore 3 database
  # @param viz Viz  (optional)
  # @return [VizResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
