# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NetworkEntity")

model_instance <- NetworkEntity$new()

test_that("id", {
  # tests for the property `id` (integer)
  # database id

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("db_identifier", {
  # tests for the property `db_identifier` (character)
  # unique identifier

  # uncomment below to test the property
  #expect_equal(model.instance$`db_identifier`, "EXPECTED_RESULT")
})

test_that("id_network", {
  # tests for the property `id_network` (integer)
  # id of the network

  # uncomment below to test the property
  #expect_equal(model.instance$`id_network`, "EXPECTED_RESULT")
})
