# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test App")

model_instance <- App$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id in database

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # title of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("sub_title", {
  # tests for the property `sub_title` (character)
  # brief description of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`sub_title`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # description of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("route", {
  # tests for the property `route` (character)
  # route of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`route`, "EXPECTED_RESULT")
})
