# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ImportSbmlApi")

api_instance <- ImportSbmlApi$new()

test_that("IMPORTSBML", {
  # tests for IMPORTSBML
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Import an SBML file
  # Import an SBML file and creates a new Network in the database. 
  # @param file data.frame The SBML file to import
  # @param name character The name of the Network
  # @param identifier character The identifier of the Network
  # @param id_collection character The id of the collection to import the Network into
  # @param ncbi_id character The ncbi id of the organism corresponding to the Network (optional)
  # @param description character The description of the Network (optional)
  # @param source character The database source of the Network (e.g KEGG, BIGG) (optional)
  # @param identifier_origin character The origin of the identifiers in the Network (e.g. KEGG, BIGG) (optional)
  # @param url character The url of the Network in the original database (optional)
  # @param version character The version of the Network (e.g. 1.0.0) (optional)
  # @param strain character The strain of the organism corresponding to the Network (e.g. K12) (optional)
  # @param tissue character The tissue of the organism corresponding to the Network (e.g. liver) (optional)
  # @param cell_type character The cell type corresponding to the Network (e.g. hepatocyte) (optional)
  # @return [ImportResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
