# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VizrightsApi")

api_instance <- VizrightsApi$new()

test_that("GETVIZRIGHTS", {
  # tests for GETVIZRIGHTS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Get permissions on a viz
  # Get the permissions on a visualisation. The user must be authenticated and have the read rights on the visualisation. 
  # @param id integer the viz id
  # @return [VizArrayRightResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
