# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddMappingAnalysesRequest")

model_instance <- AddMappingAnalysesRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # name of the mapping

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("mapping", {
  # tests for the property `mapping` (MappingOutput)

  # uncomment below to test the property
  #expect_equal(model.instance$`mapping`, "EXPECTED_RESULT")
})
