# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VizRight")

model_instance <- VizRight$new()

test_that("id_viz", {
  # tests for the property `id_viz` (integer)
  # id of the viz

  # uncomment below to test the property
  #expect_equal(model.instance$`id_viz`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # username of the user

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("permission", {
  # tests for the property `permission` (Permission)
  # permission of the user on the viz

  # uncomment below to test the property
  #expect_equal(model.instance$`permission`, "EXPECTED_RESULT")
})
