# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Viz")

model_instance <- Viz$new()

test_that("id", {
  # tests for the property `id` (integer)
  # database id

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description of the visualisation

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("date_creation", {
  # tests for the property `date_creation` (character)
  # Creation date of the Network (ISO 8601 full-time format)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_creation`, "EXPECTED_RESULT")
})

test_that("date_last_modif", {
  # tests for the property `date_last_modif` (character)
  # Last modification date of the Network (ISO 8601 full-time format)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_last_modif`, "EXPECTED_RESULT")
})

test_that("public", {
  # tests for the property `public` (numeric)
  # Indicates if the Viz is public (0 or 1)

  # uncomment below to test the property
  #expect_equal(model.instance$`public`, "EXPECTED_RESULT")
})

test_that("json", {
  # tests for the property `json` (character)
  # Json graph of the viz

  # uncomment below to test the property
  #expect_equal(model.instance$`json`, "EXPECTED_RESULT")
})

test_that("image_base64", {
  # tests for the property `image_base64` (character)
  # Base64 image of the viz

  # uncomment below to test the property
  #expect_equal(model.instance$`image_base64`, "EXPECTED_RESULT")
})

test_that("permission", {
  # tests for the property `permission` (character)
  # Permission of the user that does the query on the viz

  # uncomment below to test the property
  #expect_equal(model.instance$`permission`, "EXPECTED_RESULT")
})

test_that("favorite", {
  # tests for the property `favorite` (numeric)
  # Indicates if the Viz is favorite (0 or 1)

  # uncomment below to test the property
  #expect_equal(model.instance$`favorite`, "EXPECTED_RESULT")
})
