# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VisitsResponse")

model_instance <- VisitsResponse$new()

test_that("message", {
  # tests for the property `message` (character)
  # Message to describe that it&#39;s ok or not

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("success", {
  # tests for the property `success` (character)
  # Indicates if the response is a success or a fail

  # uncomment below to test the property
  #expect_equal(model.instance$`success`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)
  # Code of the response

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("all_visits", {
  # tests for the property `all_visits` (integer)
  # the total number of visits to the network.

  # uncomment below to test the property
  #expect_equal(model.instance$`all_visits`, "EXPECTED_RESULT")
})

test_that("user_visits", {
  # tests for the property `user_visits` (integer)
  # the number of visits to the network by the authenticated user.

  # uncomment below to test the property
  #expect_equal(model.instance$`user_visits`, "EXPECTED_RESULT")
})
