# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NetworkApi")

api_instance <- NetworkApi$new()

test_that("DELNETWORK", {
  # tests for DELNETWORK
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # delete a Metabolic Network
  # Delete a Network.
  # @param delnetwork_request DELNETWORKRequest  (optional)
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
