# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ApiApp")

model_instance <- ApiApp$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id in database

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("institution", {
  # tests for the property `institution` (character)
  # institution of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`institution`, "EXPECTED_RESULT")
})

test_that("lab", {
  # tests for the property `lab` (character)
  # lab of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`lab`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # description of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("token", {
  # tests for the property `token` (character)
  # token of the app

  # uncomment below to test the property
  #expect_equal(model.instance$`token`, "EXPECTED_RESULT")
})

test_that("protected", {
  # tests for the property `protected` (integer)
  # If an app is protected, it can&#39;t be deleted by the api.

  # uncomment below to test the property
  #expect_equal(model.instance$`protected`, "EXPECTED_RESULT")
})
