# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateMappingAnalysisRequest")

model_instance <- UpdateMappingAnalysisRequest$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id of the mapping analysis

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # new name of the analysis

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})
