# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnalysisDataApi")

api_instance <- AnalysisDataApi$new()

test_that("AddAnalysisData", {
  # tests for AddAnalysisData
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # add AnalysisData
  # add an analysis data step
  # @param analysis_data AnalysisData  (optional)
  # @return [AnalysisDataResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DelAnalysisData", {
  # tests for DelAnalysisData
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # delete AnalysisData
  # delete an analysis data step
  # @param id integer the id for the AnalysisData
  # @return [AnalysisDataResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAnalysisData", {
  # tests for GetAnalysisData
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get AnalysisData
  # get an analysis data by id or all the ones from an Analysis
  # @param id integer the id of the AnalysisData (optional)
  # @param id_analysis integer the id of the Analysis (optional)
  # @return [AnalysisDataResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateAnalysisData", {
  # tests for UpdateAnalysisData
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # update AnalysisData
  # update an analysis data step with the body of the request
  # @param analysis_data AnalysisData  (optional)
  # @return [AnalysisDataResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
