# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Analysis")

model_instance <- Analysis$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id of the analysis

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of the analysis

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # description of the analysis

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # url of the analysis

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("date_creation", {
  # tests for the property `date_creation` (character)
  # date of the creation of the analysis (ISO 8601 full-time format)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_creation`, "EXPECTED_RESULT")
})

test_that("date_edition", {
  # tests for the property `date_edition` (character)
  # date of the last modification (ISO 8601 full-time format)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_edition`, "EXPECTED_RESULT")
})
