# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DelAnalysisRequest")

model_instance <- DelAnalysisRequest$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id in database

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})
