# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MatchingApiResponseAllOfResponse")

model_instance <- MatchingApiResponseAllOfResponse$new()

test_that("Query", {
  # tests for the property `Query` (array[character])
  # list of the queries

  # uncomment below to test the property
  #expect_equal(model.instance$`Query`, "EXPECTED_RESULT")
})

test_that("Match", {
  # tests for the property `Match` (array[character])
  # names matching in the API

  # uncomment below to test the property
  #expect_equal(model.instance$`Match`, "EXPECTED_RESULT")
})

test_that("HMDB", {
  # tests for the property `HMDB` (array[character])
  # HMDB IDs

  # uncomment below to test the property
  #expect_equal(model.instance$`HMDB`, "EXPECTED_RESULT")
})

test_that("PubChem", {
  # tests for the property `PubChem` (array[character])
  # PubChem IDs

  # uncomment below to test the property
  #expect_equal(model.instance$`PubChem`, "EXPECTED_RESULT")
})

test_that("ChEBI", {
  # tests for the property `ChEBI` (array[character])
  # CHEBI IDs

  # uncomment below to test the property
  #expect_equal(model.instance$`ChEBI`, "EXPECTED_RESULT")
})

test_that("KEGG", {
  # tests for the property `KEGG` (array[character])
  # KEGG IDs

  # uncomment below to test the property
  #expect_equal(model.instance$`KEGG`, "EXPECTED_RESULT")
})

test_that("METLIN", {
  # tests for the property `METLIN` (array[character])
  # METLIN IDs

  # uncomment below to test the property
  #expect_equal(model.instance$`METLIN`, "EXPECTED_RESULT")
})

test_that("SMILES", {
  # tests for the property `SMILES` (array[character])
  # SMILES IDs

  # uncomment below to test the property
  #expect_equal(model.instance$`SMILES`, "EXPECTED_RESULT")
})

test_that("Comment", {
  # tests for the property `Comment` (array[character])
  # number of matches

  # uncomment below to test the property
  #expect_equal(model.instance$`Comment`, "EXPECTED_RESULT")
})
