# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CollectionApi")

api_instance <- CollectionApi$new()

test_that("ADDCOLLECTION", {
  # tests for ADDCOLLECTION
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # add Metabolic Network Collection
  # add a Metabolic Network Collection in the database
  # @param collection Collection  (optional)
  # @return [CollectionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DELCOLLECTION", {
  # tests for DELCOLLECTION
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # delete a Metabolic Network Collection
  # Delete a Collection.
  # @param delcollection_request DELCOLLECTIONRequest  (optional)
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GETCOLLECTIONS", {
  # tests for GETCOLLECTIONS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get Metabolic Network Collections
  # Get public and/or private Metabolic Network Collections. If the id is specified, get the collection corresponding to this id
  # @param id integer id of the app (optional)
  # @param permission Permission permission of the user on the collection (optional)
  # @return [CollectionsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
