# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MappingInputTable")

model_instance <- MappingInputTable$new()

test_that("ids", {
  # tests for the property `ids` (array[character])
  # ids

  # uncomment below to test the property
  #expect_equal(model.instance$`ids`, "EXPECTED_RESULT")
})
