# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Enrichment")

model_instance <- Enrichment$new()

test_that("label", {
  # tests for the property `label` (character)
  # label of the pathway

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("nb_total_metabolites", {
  # tests for the property `nb_total_metabolites` (integer)
  # total number of metabolites

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_metabolites`, "EXPECTED_RESULT")
})

test_that("nb_mapped_metabolites", {
  # tests for the property `nb_mapped_metabolites` (integer)
  # number of mapped metabolites

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_metabolites`, "EXPECTED_RESULT")
})

test_that("nb_total_reactions", {
  # tests for the property `nb_total_reactions` (integer)
  # total number of reactions

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_reactions`, "EXPECTED_RESULT")
})

test_that("nb_mapped_reactions", {
  # tests for the property `nb_mapped_reactions` (integer)
  # number of mapped reactions

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_reactions`, "EXPECTED_RESULT")
})

test_that("pval_metabolites", {
  # tests for the property `pval_metabolites` (numeric)
  # result of the right-tailed fisher test for metabolites

  # uncomment below to test the property
  #expect_equal(model.instance$`pval_metabolites`, "EXPECTED_RESULT")
})

test_that("bonferroni_pval_metabolites", {
  # tests for the property `bonferroni_pval_metabolites` (numeric)
  # bonferroni correction of the p-value for metabolites

  # uncomment below to test the property
  #expect_equal(model.instance$`bonferroni_pval_metabolites`, "EXPECTED_RESULT")
})

test_that("bh_pval_metabolites", {
  # tests for the property `bh_pval_metabolites` (numeric)
  # Benjamini-Hochberg correction of the p-value for metabolites

  # uncomment below to test the property
  #expect_equal(model.instance$`bh_pval_metabolites`, "EXPECTED_RESULT")
})

test_that("pval_reactions", {
  # tests for the property `pval_reactions` (numeric)
  # result of the right-tailed fisher test for reactions

  # uncomment below to test the property
  #expect_equal(model.instance$`pval_reactions`, "EXPECTED_RESULT")
})

test_that("bonferroni_pval_reactions", {
  # tests for the property `bonferroni_pval_reactions` (numeric)
  # bonferroni correction of the p-value for reactions

  # uncomment below to test the property
  #expect_equal(model.instance$`bonferroni_pval_reactions`, "EXPECTED_RESULT")
})

test_that("bh_pval_reactions", {
  # tests for the property `bh_pval_reactions` (numeric)
  # Benjamini-Hochberg correction of the p-value for reactions

  # uncomment below to test the property
  #expect_equal(model.instance$`bh_pval_reactions`, "EXPECTED_RESULT")
})
