# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MetabolitesApi")

api_instance <- MetabolitesApi$new()

test_that("GETMETABOLITES", {
  # tests for GETMETABOLITES
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get Metabolite
  # get from Metabolite
  # @param id integer the id for the Metabolite (optional)
  # @param id_network integer the id_network for the Metabolite (optional)
  # @param id_collection integer the id_collection for the Metabolite (optional)
  # @return [MetabolitesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
