# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FiltersResponse")

model_instance <- FiltersResponse$new()

test_that("message", {
  # tests for the property `message` (character)
  # Message to describe that it&#39;s ok or not

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("success", {
  # tests for the property `success` (character)
  # Indicates if the response is a success or a fail

  # uncomment below to test the property
  #expect_equal(model.instance$`success`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)
  # Code of the response

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("ids", {
  # tests for the property `ids` (array[integer])
  # array of database ids (integers)

  # uncomment below to test the property
  #expect_equal(model.instance$`ids`, "EXPECTED_RESULT")
})

test_that("db_identifiers", {
  # tests for the property `db_identifiers` (array[character])
  # array of MetExplore identifiers (strings)

  # uncomment below to test the property
  #expect_equal(model.instance$`db_identifiers`, "EXPECTED_RESULT")
})

test_that("names", {
  # tests for the property `names` (array[character])
  # array of names (strings)

  # uncomment below to test the property
  #expect_equal(model.instance$`names`, "EXPECTED_RESULT")
})
