# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatisticsMapping")

model_instance <- StatisticsMapping$new()

test_that("nb_queries", {
  # tests for the property `nb_queries` (integer)
  # total number of queries in the mapping

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_queries`, "EXPECTED_RESULT")
})

test_that("nb_mapped_queries", {
  # tests for the property `nb_mapped_queries` (integer)
  # number of mapped queries

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_queries`, "EXPECTED_RESULT")
})

test_that("nb_mapped_pathways", {
  # tests for the property `nb_mapped_pathways` (integer)
  # number of mapped pathways

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_pathways`, "EXPECTED_RESULT")
})

test_that("nb_total_pathways", {
  # tests for the property `nb_total_pathways` (integer)
  # total number of pathways

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_pathways`, "EXPECTED_RESULT")
})

test_that("nb_mapped_reactions", {
  # tests for the property `nb_mapped_reactions` (integer)
  # number of mapped reactions

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_reactions`, "EXPECTED_RESULT")
})

test_that("nb_total_reactions", {
  # tests for the property `nb_total_reactions` (integer)
  # total number of reactions

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_reactions`, "EXPECTED_RESULT")
})

test_that("nb_mapped_metabolites", {
  # tests for the property `nb_mapped_metabolites` (integer)
  # number of mapped metabolites

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_metabolites`, "EXPECTED_RESULT")
})

test_that("nb_total_metabolites", {
  # tests for the property `nb_total_metabolites` (integer)
  # total number of metabolites

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_metabolites`, "EXPECTED_RESULT")
})

test_that("nb_mapped_genes", {
  # tests for the property `nb_mapped_genes` (integer)
  # number of mapped metabolites

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_genes`, "EXPECTED_RESULT")
})

test_that("nb_total_genes", {
  # tests for the property `nb_total_genes` (integer)
  # total number of genes

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_genes`, "EXPECTED_RESULT")
})

test_that("nb_mapped_gene_products", {
  # tests for the property `nb_mapped_gene_products` (integer)
  # number of mapped gene_products

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_gene_products`, "EXPECTED_RESULT")
})

test_that("nb_total_gene_products", {
  # tests for the property `nb_total_gene_products` (integer)
  # total number of gene_products

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_gene_products`, "EXPECTED_RESULT")
})

test_that("nb_mapped_enzymes", {
  # tests for the property `nb_mapped_enzymes` (integer)
  # number of mapped enzymes

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_enzymes`, "EXPECTED_RESULT")
})

test_that("nb_total_enzymes", {
  # tests for the property `nb_total_enzymes` (integer)
  # total number of enzymes

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_enzymes`, "EXPECTED_RESULT")
})

test_that("nb_mapped_compartments", {
  # tests for the property `nb_mapped_compartments` (integer)
  # number of mapped compartments

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_mapped_compartments`, "EXPECTED_RESULT")
})

test_that("nb_total_compartments", {
  # tests for the property `nb_total_compartments` (integer)
  # total number of compartments

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_total_compartments`, "EXPECTED_RESULT")
})

test_that("enrichment", {
  # tests for the property `enrichment` (map(Enrichment))
  # Object that maps strings (the keys) to Enrichment objects (the values)

  # uncomment below to test the property
  #expect_equal(model.instance$`enrichment`, "EXPECTED_RESULT")
})
