# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MappingQuery")

model_instance <- MappingQuery$new()

test_that("entries", {
  # tests for the property `entries` (MappingInputTable)

  # uncomment below to test the property
  #expect_equal(model.instance$`entries`, "EXPECTED_RESULT")
})

test_that("id_network", {
  # tests for the property `id_network` (integer)
  # id of the network in the database

  # uncomment below to test the property
  #expect_equal(model.instance$`id_network`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of the mapping

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})
