# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Step")

model_instance <- Step$new()

test_that("id", {
  # tests for the property `id` (integer)
  # step id

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("id_analysis", {
  # tests for the property `id_analysis` (integer)
  # analysis id

  # uncomment below to test the property
  #expect_equal(model.instance$`id_analysis`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of the step

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("root", {
  # tests for the property `root` (character)
  # Boolean that determined if its the first step of analysis or not

  # uncomment below to test the property
  #expect_equal(model.instance$`root`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # Determine what types (data, job, ...) is this step

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description of the step

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})
