# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnalysesApi")

api_instance <- AnalysesApi$new()

test_that("AddAnalysis", {
  # tests for AddAnalysis
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # add Analysis
  # add an Analysis with data in the body of the request as json (name, description and url)
  # @param analysis Analysis  (optional)
  # @return [AnalysisResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DelAnalysis", {
  # tests for DelAnalysis
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # delete Analysis
  # delete the Analysis with its id
  # @param del_analysis_request DelAnalysisRequest  (optional)
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAnalyses", {
  # tests for GetAnalyses
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get Analyses
  # get data from Analyses : if no id specified, all the analyses ; else only the one with corresponding id
  # @param id integer id of the analysis (optional)
  # @return [AnalysesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateAnalysis", {
  # tests for UpdateAnalysis
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # update Analysis
  # update one Analysis with its id, the data to modify is passed in the body of the request in json format (name, description, url)
  # @param analysis Analysis  (optional)
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
