# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnalysisMapping")

model_instance <- AnalysisMapping$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id of the analysis

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name of the analysis

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("json", {
  # tests for the property `json` (character)
  # json of the mapping response

  # uncomment below to test the property
  #expect_equal(model.instance$`json`, "EXPECTED_RESULT")
})
