# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobsApi")

api_instance <- JobsApi$new()

test_that("GETJOBS", {
  # tests for GETJOBS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get jobs
  # get all the jobs of a user or one job if the id is provided
  # @param id character the job id (optional)
  # @return [GETJOBS200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
