# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EnzymesApi")

api_instance <- EnzymesApi$new()

test_that("GETENZYMES", {
  # tests for GETENZYMES
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get Enzyme
  # get from Enzyme
  # @param id_network integer the id of the network
  # @return [EnzymesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
