# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StepUpdate")

model_instance <- StepUpdate$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id of the step in the MetExplore database

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("column", {
  # tests for the property `column` (character)
  # Column name to update

  # uncomment below to test the property
  #expect_equal(model.instance$`column`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)
  # New value for the column

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})
