# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CompartmentsApi")

api_instance <- CompartmentsApi$new()

test_that("GETCOMPARTMENTS", {
  # tests for GETCOMPARTMENTS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get compartments in a network
  # get compartments in a network
  # @param id_network integer the id of the network
  # @return [CompartmentsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
