# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NetworksApi")

api_instance <- NetworksApi$new()

test_that("ADDNETWORK", {
  # tests for ADDNETWORK
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # add a Network
  # add a Network in a Collection
  # @param network array[Network]  (optional)
  # @return [NetworkResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GETNETWORKS", {
  # tests for GETNETWORKS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Get all networks
  # Get all networks or one network if the id is provided. If a user is authenticated, get both public and private networks. If a network id is provided, the user must have the read rights on the network 
  # @param id integer the network id (optional)
  # @param format character format of the output (optional)
  # @return [GETNETWORKS200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UPDATENETWORK", {
  # tests for UPDATENETWORK
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # update a Metabolic Networ
  # Update a Metabolic Network
  # @param network Network  (optional)
  # @return [NetworkResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
