# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GenesApi")

api_instance <- GenesApi$new()

test_that("GETGENES", {
  # tests for GETGENES
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get Gene
  # get from Gene
  # @param id_network integer the id_network for the Gene
  # @return [GenesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
