# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("Root", {
  # tests for Root
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Root of metexplore3-api
  # Root of metexplore3-api
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
