# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CountResponseAllOfCount")

model_instance <- CountResponseAllOfCount$new()

test_that("pathways", {
  # tests for the property `pathways` (integer)
  # The number of pathways in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`pathways`, "EXPECTED_RESULT")
})

test_that("reactions", {
  # tests for the property `reactions` (integer)
  # The number of reactions in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`reactions`, "EXPECTED_RESULT")
})

test_that("metabolites", {
  # tests for the property `metabolites` (integer)
  # The number of metabolites in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`metabolites`, "EXPECTED_RESULT")
})

test_that("enzymes", {
  # tests for the property `enzymes` (integer)
  # The number of enzymes in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`enzymes`, "EXPECTED_RESULT")
})

test_that("proteins", {
  # tests for the property `proteins` (integer)
  # The number of proteins in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`proteins`, "EXPECTED_RESULT")
})

test_that("genes", {
  # tests for the property `genes` (integer)
  # The number of genes in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`genes`, "EXPECTED_RESULT")
})

test_that("compartments", {
  # tests for the property `compartments` (integer)
  # The number of compartments in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`compartments`, "EXPECTED_RESULT")
})
