# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Filter")

model_instance <- Filter$new()

test_that("filtertype", {
  # tests for the property `filtertype` (character)
  # type of filter

  # uncomment below to test the property
  #expect_equal(model.instance$`filtertype`, "EXPECTED_RESULT")
})

test_that("ids", {
  # tests for the property `ids` (array[integer])
  # array ids of 

  # uncomment below to test the property
  #expect_equal(model.instance$`ids`, "EXPECTED_RESULT")
})
