# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Job")

model_instance <- Job$new()

test_that("id", {
  # tests for the property `id` (character)
  # id of the job

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # title of the job

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)
  # status of the job

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("log", {
  # tests for the property `log` (character)
  # log of the job

  # uncomment below to test the property
  #expect_equal(model.instance$`log`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)
  # date of the job

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)
  # message of the job

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("result", {
  # tests for the property `result` (character)
  # result of the job

  # uncomment below to test the property
  #expect_equal(model.instance$`result`, "EXPECTED_RESULT")
})
