# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ReactionsApi")

api_instance <- ReactionsApi$new()

test_that("GETREACTIONS", {
  # tests for GETREACTIONS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get Reaction
  # getReaction from Reaction
  # @param id_network integer the id of the network (optional)
  # @param id_collection integer the id of the collection for the Reaction (optional)
  # @return [ReactionsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
