# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ApiAppsApi")

api_instance <- ApiAppsApi$new()

test_that("AddApp", {
  # tests for AddApp
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # add an app and generate a token
  # add an app and generate a token
  # @param api_app array[ApiApp]  (optional)
  # @return [ApiAppResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DelApiApp", {
  # tests for DelApiApp
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # delete an api app. Requires admin authentification
  # Delete an api app. Requires admin authentification. The app that are protected can&#39;t be deleted by the api.
  # @param del_analysis_request DelAnalysisRequest  (optional)
  # @return [BaseResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetApiApps", {
  # tests for GetApiApps
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get api apps
  # get api apps : if no id specified, all the apps ; else only the one with corresponding id. Must be in admin mode.
  # @param id integer id of the app (optional)
  # @return [ApiAppsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateApiApp", {
  # tests for UpdateApiApp
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # update Api App
  # Update one Api App with its id, the data to modify is passed in the body of the request in json format. Name, id, and protected can not be changed. Must be connected as admin.
  # @param api_app ApiApp  (optional)
  # @return [ApiAppsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
