# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CollectionsApi")

api_instance <- CollectionsApi$new()

test_that("UPDATECOLLECTION", {
  # tests for UPDATECOLLECTION
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # update a Metabolic Network Collection
  # Update a Metabolic Network Collection
  # @param collection Collection  (optional)
  # @return [CollectionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
