# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnalysisDataResponse")

model_instance <- AnalysisDataResponse$new()

test_that("message", {
  # tests for the property `message` (character)
  # Message to describe that it&#39;s ok or not

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("success", {
  # tests for the property `success` (character)
  # Indicates if the response is a success or a fail

  # uncomment below to test the property
  #expect_equal(model.instance$`success`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)
  # Code of the response

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("analysisData", {
  # tests for the property `analysisData` (array[AnalysisData])
  # array of AnalysisData objects

  # uncomment below to test the property
  #expect_equal(model.instance$`analysisData`, "EXPECTED_RESULT")
})
