# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Network")

model_instance <- Network$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id of the Network in the MetExplore database

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Nick name of the Network

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("id_collection", {
  # tests for the property `id_collection` (integer)
  # Database id of the collection to which the network belongs

  # uncomment below to test the property
  #expect_equal(model.instance$`id_collection`, "EXPECTED_RESULT")
})

test_that("ncbi_id", {
  # tests for the property `ncbi_id` (integer)
  # NCBI taxonomy id

  # uncomment below to test the property
  #expect_equal(model.instance$`ncbi_id`, "EXPECTED_RESULT")
})

test_that("organism_name", {
  # tests for the property `organism_name` (character)
  # Organism name

  # uncomment below to test the property
  #expect_equal(model.instance$`organism_name`, "EXPECTED_RESULT")
})

test_that("db_identifier", {
  # tests for the property `db_identifier` (character)
  # identifier of the network in the original database

  # uncomment below to test the property
  #expect_equal(model.instance$`db_identifier`, "EXPECTED_RESULT")
})

test_that("strain", {
  # tests for the property `strain` (character)
  # Strain of the organism

  # uncomment below to test the property
  #expect_equal(model.instance$`strain`, "EXPECTED_RESULT")
})

test_that("tissue", {
  # tests for the property `tissue` (character)
  # Tissue corresponding to the Network

  # uncomment below to test the property
  #expect_equal(model.instance$`tissue`, "EXPECTED_RESULT")
})

test_that("cell_type", {
  # tests for the property `cell_type` (character)
  # Cell type corresponding to the Network

  # uncomment below to test the property
  #expect_equal(model.instance$`cell_type`, "EXPECTED_RESULT")
})

test_that("source", {
  # tests for the property `source` (character)
  # Source of the network

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Version of the network

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description of the network

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # Url of the network

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("identifier_origin", {
  # tests for the property `identifier_origin` (character)
  # Origin of the identifiers in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`identifier_origin`, "EXPECTED_RESULT")
})

test_that("date_creation", {
  # tests for the property `date_creation` (character)
  # Creation date of the Network (ISO 8601 full-time format)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_creation`, "EXPECTED_RESULT")
})

test_that("date_last_modif", {
  # tests for the property `date_last_modif` (character)
  # Last modification date of the Network (ISO 8601 full-time format)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_last_modif`, "EXPECTED_RESULT")
})

test_that("top", {
  # tests for the property `top` (integer)
  # Indicates if the Network is among the top Networks in MetExplore

  # uncomment below to test the property
  #expect_equal(model.instance$`top`, "EXPECTED_RESULT")
})

test_that("visits", {
  # tests for the property `visits` (integer)
  # Number of times where this Network has been selected

  # uncomment below to test the property
  #expect_equal(model.instance$`visits`, "EXPECTED_RESULT")
})

test_that("permission", {
  # tests for the property `permission` (Permission)
  # Permission of the user on the network

  # uncomment below to test the property
  #expect_equal(model.instance$`permission`, "EXPECTED_RESULT")
})

test_that("nb_pathways", {
  # tests for the property `nb_pathways` (integer)
  # number of pathways in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_pathways`, "EXPECTED_RESULT")
})

test_that("nb_reactions", {
  # tests for the property `nb_reactions` (integer)
  # number of reactions in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_reactions`, "EXPECTED_RESULT")
})

test_that("nb_metabolites", {
  # tests for the property `nb_metabolites` (integer)
  # number of metabolites in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_metabolites`, "EXPECTED_RESULT")
})

test_that("nb_genes", {
  # tests for the property `nb_genes` (integer)
  # number of genes in the network

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_genes`, "EXPECTED_RESULT")
})

test_that("user_visits", {
  # tests for the property `user_visits` (integer)
  # Number of visits to the network by the authenticated user

  # uncomment below to test the property
  #expect_equal(model.instance$`user_visits`, "EXPECTED_RESULT")
})
