# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test User")

model_instance <- User$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id of the user in the MetExplore database

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("full_name", {
  # tests for the property `full_name` (character)
  # Full name of the user

  # uncomment below to test the property
  #expect_equal(model.instance$`full_name`, "EXPECTED_RESULT")
})

test_that("login", {
  # tests for the property `login` (character)
  # Name of the user, used to logged in

  # uncomment below to test the property
  #expect_equal(model.instance$`login`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)
  # email of the user

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)
  # Password of the user

  # uncomment below to test the property
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})

test_that("last_visit_date", {
  # tests for the property `last_visit_date` (character)
  # Date of the user&#39;s last visit

  # uncomment below to test the property
  #expect_equal(model.instance$`last_visit_date`, "EXPECTED_RESULT")
})

test_that("registration_date", {
  # tests for the property `registration_date` (character)
  # Date of the user&#39;s registration

  # uncomment below to test the property
  #expect_equal(model.instance$`registration_date`, "EXPECTED_RESULT")
})

test_that("token", {
  # tests for the property `token` (character)
  # token of the user, returned when login

  # uncomment below to test the property
  #expect_equal(model.instance$`token`, "EXPECTED_RESULT")
})
