# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AppsApi")

api_instance <- AppsApi$new()

test_that("GETAPPS", {
  # tests for GETAPPS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get MetExplore apps
  # get the list and description of the MetExplore apps
  # @param id integer id of the app (optional)
  # @return [GETAPPS200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
