# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Reaction")

model_instance <- Reaction$new()

test_that("id", {
  # tests for the property `id` (integer)
  # database id

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("db_identifier", {
  # tests for the property `db_identifier` (character)
  # unique identifier

  # uncomment below to test the property
  #expect_equal(model.instance$`db_identifier`, "EXPECTED_RESULT")
})

test_that("id_collection", {
  # tests for the property `id_collection` (integer)
  # id of the collection

  # uncomment below to test the property
  #expect_equal(model.instance$`id_collection`, "EXPECTED_RESULT")
})

test_that("spontaneous", {
  # tests for the property `spontaneous` (numeric)
  # spontaneous for Reaction (0 : false, 1 : true)

  # uncomment below to test the property
  #expect_equal(model.instance$`spontaneous`, "EXPECTED_RESULT")
})

test_that("generic", {
  # tests for the property `generic` (numeric)
  # generic for Reaction (0 : false, 1 : true)

  # uncomment below to test the property
  #expect_equal(model.instance$`generic`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # type for Reaction

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("ec", {
  # tests for the property `ec` (character)
  # ec for Reaction

  # uncomment below to test the property
  #expect_equal(model.instance$`ec`, "EXPECTED_RESULT")
})

test_that("id_last_annotator", {
  # tests for the property `id_last_annotator` (integer)
  # id_last_annotator for Reaction

  # uncomment below to test the property
  #expect_equal(model.instance$`id_last_annotator`, "EXPECTED_RESULT")
})

test_that("date_modification", {
  # tests for the property `date_modification` (object)
  # date_modification for Reaction

  # uncomment below to test the property
  #expect_equal(model.instance$`date_modification`, "EXPECTED_RESULT")
})

test_that("reversible", {
  # tests for the property `reversible` (numeric)
  # reversible for Reaction (0 : false, 1 : true)

  # uncomment below to test the property
  #expect_equal(model.instance$`reversible`, "EXPECTED_RESULT")
})

test_that("eq_identifier", {
  # tests for the property `eq_identifier` (character)
  # Equation with identifiers

  # uncomment below to test the property
  #expect_equal(model.instance$`eq_identifier`, "EXPECTED_RESULT")
})

test_that("eq_name", {
  # tests for the property `eq_name` (character)
  # Equation with names

  # uncomment below to test the property
  #expect_equal(model.instance$`eq_name`, "EXPECTED_RESULT")
})
