# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test COPYVIZRequest")

model_instance <- COPYVIZRequest$new()

test_that("id", {
  # tests for the property `id` (integer)
  # the viz id

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})
