# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MappingAnalysesApi")

api_instance <- MappingAnalysesApi$new()

test_that("AddMappingAnalyses", {
  # tests for AddMappingAnalyses
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # add Mapping Analysis
  # add an mapping Analysis with data in the body of the request as json (MappingResponse)
  # @param add_mapping_analyses_request AddMappingAnalysesRequest  (optional)
  # @return [AnalysisResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DelMappingAnalyses", {
  # tests for DelMappingAnalyses
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # delete Mapping Analysis
  # delete the mapping Analysis with its id
  # @param del_analysis_request DelAnalysisRequest  (optional)
  # @return [AnalysesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetMappingAnalyses", {
  # tests for GetMappingAnalyses
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get mapping Analysis
  # get data from mapping Analysis : if no id specified, all the mapping analyses ; else only the one with corresponding id
  # @param id integer id of the mapping analysis (optional)
  # @return [AnalysesMappingResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateMappingAnalysis", {
  # tests for UpdateMappingAnalysis
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # update mapping Analysis
  # update a mapping Analysis with its id, the data to modify is passed in the body of the request in json format (name)
  # @param update_mapping_analysis_request UpdateMappingAnalysisRequest 
  # @return [AnalysesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
