# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Compartment")

model_instance <- Compartment$new()

test_that("id", {
  # tests for the property `id` (integer)
  # database id

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # name

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("db_identifier", {
  # tests for the property `db_identifier` (character)
  # unique identifier

  # uncomment below to test the property
  #expect_equal(model.instance$`db_identifier`, "EXPECTED_RESULT")
})

test_that("id_network", {
  # tests for the property `id_network` (integer)
  # id of the network

  # uncomment below to test the property
  #expect_equal(model.instance$`id_network`, "EXPECTED_RESULT")
})

test_that("spatial_dimensions", {
  # tests for the property `spatial_dimensions` (integer)
  # number of spatial dimensions possessed by the compartment

  # uncomment below to test the property
  #expect_equal(model.instance$`spatial_dimensions`, "EXPECTED_RESULT")
})

test_that("units", {
  # tests for the property `units` (character)
  # measurement unit associated with the value of the compartment’s size attribute

  # uncomment below to test the property
  #expect_equal(model.instance$`units`, "EXPECTED_RESULT")
})

test_that("constant", {
  # tests for the property `constant` (integer)
  # indicates whether the compart41 ment’s size stays constant (1) or can vary during a simulation (0)

  # uncomment below to test the property
  #expect_equal(model.instance$`constant`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)
  # can be used to set the initial size of the compartment. The size may correspond to a volume (if the compartment is a three-dimensional one), or it may be an area (if the compartment is two-dimensional), or a length (if the compartment is one-dimensional)

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})
