# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProteinsApi")

api_instance <- ProteinsApi$new()

test_that("GETPROTEINS", {
  # tests for GETPROTEINS
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # get Protein
  # get from Protein
  # @param id integer the id for the Protein (optional)
  # @param id_network integer the id_network for the Protein (optional)
  # @param id_collection integer the id_collection for the Protein (optional)
  # @return [ProteinsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
