# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Collection")

model_instance <- Collection$new()

test_that("id", {
  # tests for the property `id` (integer)
  # id of the Collection: in the MetExplore database

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of the Collection

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description of the collection

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("nb_networks", {
  # tests for the property `nb_networks` (integer)
  # Number of networks in the collection

  # uncomment below to test the property
  #expect_equal(model.instance$`nb_networks`, "EXPECTED_RESULT")
})
