# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MappingResponse")

model_instance <- MappingResponse$new()

test_that("message", {
  # tests for the property `message` (character)
  # Message to describe that it&#39;s ok or not

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("success", {
  # tests for the property `success` (character)
  # Indicates if the response is a success or a fail

  # uncomment below to test the property
  #expect_equal(model.instance$`success`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)
  # Code of the response

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("input", {
  # tests for the property `input` (MappingQuery)

  # uncomment below to test the property
  #expect_equal(model.instance$`input`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)
  # Creation date of the mapping

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("map", {
  # tests for the property `map` (object)
  # mapping between the entries and the metabolic identifiers in MetExplore

  # uncomment below to test the property
  #expect_equal(model.instance$`map`, "EXPECTED_RESULT")
})

test_that("entities", {
  # tests for the property `entities` (MappingOutputEntities)

  # uncomment below to test the property
  #expect_equal(model.instance$`entities`, "EXPECTED_RESULT")
})

test_that("statistics", {
  # tests for the property `statistics` (StatisticsMapping)

  # uncomment below to test the property
  #expect_equal(model.instance$`statistics`, "EXPECTED_RESULT")
})
