# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StepsApi")

api_instance <- StepsApi$new()

test_that("AddSteps", {
  # tests for AddSteps
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # add step
  # add a step for a specific analysis
  # @param step_response array[StepResponse]  (optional)
  # @return [StepResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DelStep", {
  # tests for DelStep
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Remove a step
  # delete a Step in an analysis
  # @param id integer the id for the Step (optional)
  # @return [StepResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetSteps", {
  # tests for GetSteps
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Get specific step of an analysis
  # Get a specific step of an analysis
  # @param id integer the id for the step (optional)
  # @param id_analysis integer the id for an analysis (optional)
  # @return [StepResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateSteps", {
  # tests for UpdateSteps
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # update Step
  # update a step for a specific analysis
  # @param step_update array[StepUpdate]  (optional)
  # @return [StepResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
