# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Graph")

model_instance <- Graph$new()

test_that("directed", {
  # tests for the property `directed` (character)
  # the graph mode (e.g. directed or undirected).

  # uncomment below to test the property
  #expect_equal(model.instance$`directed`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # classification for the graph

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("label", {
  # tests for the property `label` (character)
  # text display

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (map(AnyType))

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("nodes", {
  # tests for the property `nodes` (map(Node))
  # nodes of the graph

  # uncomment below to test the property
  #expect_equal(model.instance$`nodes`, "EXPECTED_RESULT")
})

test_that("edges", {
  # tests for the property `edges` (array[Edge])
  # edges of the graph

  # uncomment below to test the property
  #expect_equal(model.instance$`edges`, "EXPECTED_RESULT")
})
