# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersApi")

api_instance <- UsersApi$new()

test_that("UserCreate", {
  # tests for UserCreate
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Create user into the system
  # @param user User  (optional)
  # @return [UserResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UserLogin", {
  # tests for UserLogin
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Logs user into the system
  # @param user User  (optional)
  # @return [UserResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UserTokenLogin", {
  # tests for UserTokenLogin
  # base path: https://metexplore.toulouse.inrae.fr/metexplore3-api
  # Logs user into the system with a token
  # @return [UserResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
