#' MetExplore 3 REST api
#'
#' Rest API for [MetExplore](https://metexplore.toulouse.inrae.fr/index.html/) content.
#'
#' The version of the OpenAPI document: 0.19.0-pre-release
#' Contact: contact-metexplore@inrae.fr
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title ImportSbml operations
#' @description ImportSbmlApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  IMPORTSBML  ####################
#'
#' library(metexplore3api?)
#' var_file <- File.new('/path/to/file') # data.frame | The SBML file to import
#' var_name <- "name_example" # character | The name of the Network
#' var_identifier <- "identifier_example" # character | The identifier of the Network
#' var_id_collection <- "id_collection_example" # character | The id of the collection to import the Network into
#' var_ncbi_id <- "12908" # character | The ncbi id of the organism corresponding to the Network (Optional)
#' var_description <- "description_example" # character | The description of the Network (Optional)
#' var_source <- "unknown" # character | The database source of the Network (e.g KEGG, BIGG) (Optional)
#' var_identifier_origin <- "identifier_origin_example" # character | The origin of the identifiers in the Network (e.g. KEGG, BIGG) (Optional)
#' var_url <- "url_example" # character | The url of the Network in the original database (Optional)
#' var_version <- "version_example" # character | The version of the Network (e.g. 1.0.0) (Optional)
#' var_strain <- "strain_example" # character | The strain of the organism corresponding to the Network (e.g. K12) (Optional)
#' var_tissue <- "tissue_example" # character | The tissue of the organism corresponding to the Network (e.g. liver) (Optional)
#' var_cell_type <- "cell_type_example" # character | The cell type corresponding to the Network (e.g. hepatocyte) (Optional)
#'
#' #Import an SBML file
#' api_instance <- ImportSbmlApi$new()
#'
#' # Configure HTTP bearer authorization: userAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # Configure API key authorization: appAuth
#' api_instance$api_client$api_keys["x-app-key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$IMPORTSBML(var_file, var_name, var_identifier, var_id_collection, ncbi_id = var_ncbi_id, description = var_description, source = var_source, identifier_origin = var_identifier_origin, url = var_url, version = var_version, strain = var_strain, tissue = var_tissue, cell_type = var_cell_typedata_file = "result.txt")
#' result <- api_instance$IMPORTSBML(var_file, var_name, var_identifier, var_id_collection, ncbi_id = var_ncbi_id, description = var_description, source = var_source, identifier_origin = var_identifier_origin, url = var_url, version = var_version, strain = var_strain, tissue = var_tissue, cell_type = var_cell_type)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
ImportSbmlApi <- R6::R6Class(
  "ImportSbmlApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new ImportSbmlApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Import an SBML file
    #'
    #' @param file The SBML file to import
    #' @param name The name of the Network
    #' @param identifier The identifier of the Network
    #' @param id_collection The id of the collection to import the Network into
    #' @param ncbi_id (optional) The ncbi id of the organism corresponding to the Network (default value: "12908")
    #' @param description (optional) The description of the Network
    #' @param source (optional) The database source of the Network (e.g KEGG, BIGG) (default value: "unknown")
    #' @param identifier_origin (optional) The origin of the identifiers in the Network (e.g. KEGG, BIGG)
    #' @param url (optional) The url of the Network in the original database
    #' @param version (optional) The version of the Network (e.g. 1.0.0)
    #' @param strain (optional) The strain of the organism corresponding to the Network (e.g. K12)
    #' @param tissue (optional) The tissue of the organism corresponding to the Network (e.g. liver)
    #' @param cell_type (optional) The cell type corresponding to the Network (e.g. hepatocyte)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return ImportResponse
    IMPORTSBML = function(file, name, identifier, id_collection, ncbi_id = "12908", description = NULL, source = "unknown", identifier_origin = NULL, url = NULL, version = NULL, strain = NULL, tissue = NULL, cell_type = NULL, data_file = NULL, ...) {
      local_var_response <- self$IMPORTSBMLWithHttpInfo(file, name, identifier, id_collection, ncbi_id, description, source, identifier_origin, url, version, strain, tissue, cell_type, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },

    #' @description
    #' Import an SBML file
    #'
    #' @param file The SBML file to import
    #' @param name The name of the Network
    #' @param identifier The identifier of the Network
    #' @param id_collection The id of the collection to import the Network into
    #' @param ncbi_id (optional) The ncbi id of the organism corresponding to the Network (default value: "12908")
    #' @param description (optional) The description of the Network
    #' @param source (optional) The database source of the Network (e.g KEGG, BIGG) (default value: "unknown")
    #' @param identifier_origin (optional) The origin of the identifiers in the Network (e.g. KEGG, BIGG)
    #' @param url (optional) The url of the Network in the original database
    #' @param version (optional) The version of the Network (e.g. 1.0.0)
    #' @param strain (optional) The strain of the organism corresponding to the Network (e.g. K12)
    #' @param tissue (optional) The tissue of the organism corresponding to the Network (e.g. liver)
    #' @param cell_type (optional) The cell type corresponding to the Network (e.g. hepatocyte)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (ImportResponse) with additional information such as HTTP status code, headers
    IMPORTSBMLWithHttpInfo = function(file, name, identifier, id_collection, ncbi_id = "12908", description = NULL, source = "unknown", identifier_origin = NULL, url = NULL, version = NULL, strain = NULL, tissue = NULL, cell_type = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`file`)) {
        stop("Missing required parameter `file`.")
      }

      if (missing(`name`)) {
        stop("Missing required parameter `name`.")
      }

      if (missing(`identifier`)) {
        stop("Missing required parameter `identifier`.")
      }

      if (missing(`id_collection`)) {
        stop("Missing required parameter `id_collection`.")
      }














      file_params["file"] <- httr::upload_file(`file`)
      form_params["name"] <- `name`
      form_params["identifier"] <- `identifier`
      form_params["id_collection"] <- `id_collection`
      form_params["ncbi_id"] <- `ncbi_id`
      form_params["description"] <- `description`
      form_params["source"] <- `source`
      form_params["identifier_origin"] <- `identifier_origin`
      form_params["url"] <- `url`
      form_params["version"] <- `version`
      form_params["strain"] <- `strain`
      form_params["tissue"] <- `tissue`
      form_params["cell_type"] <- `cell_type`
      local_var_url_path <- "/import/sbml"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }
      # API key authentication
      if ("x-app-key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["x-app-key"]) > 0) {
        header_params["x-app-key"] <- paste(unlist(self$api_client$api_keys["x-app-key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("multipart/form-data")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "ImportResponse", loadNamespace("metexplore3api?")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
