#' MetExplore 3 REST api
#'
#' Rest API for [MetExplore](https://metexplore.toulouse.inrae.fr/index.html/) content.
#'
#' The version of the OpenAPI document: 0.29.0
#' Contact: contact-metexplore@inrae.fr
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Networks operations
#' @description NetworksApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  GETNETWORKS  ####################
#'
#' library(metexplore3api)
#' var_id <- 56 # integer | the network id (Optional)
#' var_format <- "summary" # character | format of the output (Optional)
#' var_pathway <- "pathway_example" # character | the pathway(s) id (Optional)
#' var_compartment <- "compartment_example" # character | the compartment(s) id (Optional)
#'
#' #Get all networks or one network
#' api_instance <- NetworksApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GETNETWORKS(id = var_id, format = var_format, pathway = var_pathway, compartment = var_compartmentdata_file = "result.txt")
#' result <- api_instance$GETNETWORKS(id = var_id, format = var_format, pathway = var_pathway, compartment = var_compartment)
#' dput(result)
#'
#'
#' ####################  NETWORKCOUNT  ####################
#'
#' library(metexplore3api)
#' var_id <- 56 # integer | the network id
#'
#' #get the number of all biodatas in a network
#' api_instance <- NetworksApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$NETWORKCOUNT(var_iddata_file = "result.txt")
#' result <- api_instance$NETWORKCOUNT(var_id)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
NetworksApi <- R6::R6Class(
  "NetworksApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new NetworksApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Get all networks or one network
    #'
    #' @param id (optional) the network id
    #' @param format (optional) format of the output (default value: "summary")
    #' @param pathway (optional) the pathway(s) id
    #' @param compartment (optional) the compartment(s) id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return GETNETWORKS200Response
    GETNETWORKS = function(id = NULL, format = "summary", pathway = NULL, compartment = NULL, data_file = NULL, ...) {
      local_var_response <- self$GETNETWORKSWithHttpInfo(id, format, pathway, compartment, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },

    #' @description
    #' Get all networks or one network
    #'
    #' @param id (optional) the network id
    #' @param format (optional) format of the output (default value: "summary")
    #' @param pathway (optional) the pathway(s) id
    #' @param compartment (optional) the compartment(s) id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (GETNETWORKS200Response) with additional information such as HTTP status code, headers
    GETNETWORKSWithHttpInfo = function(id = NULL, format = "summary", pathway = NULL, compartment = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE





      query_params[["id"]] <- `id`

      if (!is.null(`format`) && !(`format` %in% c("graph", "summary"))) {
        stop("Invalid value for format when calling NetworksApi$GETNETWORKS. Must be [graph, summary].")
      }
      query_params[["format"]] <- `format`

      query_params[["pathway"]] <- `pathway`

      query_params[["compartment"]] <- `compartment`

      local_var_url_path <- "/networks"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "GETNETWORKS200Response", loadNamespace("metexplore3api")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },

    #' @description
    #' get the number of all biodatas in a network
    #'
    #' @param id the network id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return CountResponse
    NETWORKCOUNT = function(id, data_file = NULL, ...) {
      local_var_response <- self$NETWORKCOUNTWithHttpInfo(id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },

    #' @description
    #' get the number of all biodatas in a network
    #'
    #' @param id the network id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (CountResponse) with additional information such as HTTP status code, headers
    NETWORKCOUNTWithHttpInfo = function(id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }


      query_params[["id"]] <- `id`

      local_var_url_path <- "/networks/count"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "CountResponse", loadNamespace("metexplore3api")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
